export enum ACTIONS_TYPE {
    INCREASE_CURRENT_VALUE= 'increase_current_value/INCREASE_CURRENT_VALUE',
    DECREASE_CURRENT_VALUE= 'decrease_current_value/DECREASE_CURRENT_VALUE',
    CHANGE_START_VALUE='change_start_value/CHANGE_START_VALUE',
    CHANGE_FINISH_VALUE='change_finish_value/CHANGE_FINISH_VALUE',
    CHANGE_CONDITION_OF_WORK='change_condition_of_work/CHANGE_CONDITION_OF_WORK',
    SET_AUTOPLAY_OPTION='set_autoplay_option/SET_AUTOPLAY_OPTION'
}